import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useEffect, useState, useRef } from "react";
import Web3 from "web3";
import { useWeb3React, Web3ReactProvider } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import { WalletConnectConnector } from "@web3-react/walletconnect-connector";

const injected = new InjectedConnector({ supportedChainIds: [1, 3, 4, 5, 42] });
const wcConnector = new WalletConnectConnector({
  infuraId: "517bf3874a6848e58f99fa38ccf9fce4",
});

function getLibrary(provider) {
  return new Web3(provider);
}

export default function WrapperHome() {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <Home />
    </Web3ReactProvider>
  );
}

function Home() {
  const web3React = useWeb3React();

  console.log(web3React);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        onClick={() => {
          console.log("metamask clicked");
          web3React.activate(injected);
        }}
      >
        connect to metamask
      </div>
      <div
        onClick={() => {
          web3React.activate(wcConnector);
        }}
      >
        walletconnect
      </div>
      {web3React.active ? <div>Connected as {web3React.account}</div> : null}

      {web3React.active ? (
        <div onClick={() => web3React.deactivate()}>disconnect</div>
      ) : null}
    </div>
  );
}
